import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, Outlet, RouterProvider, createRootRoute, createRoute, createRouter } from "@tanstack/react-router";
import { api, isActive, saveAsset, useDraft, type Job } from "./api";
import type { AssetRow } from "../../src/web-types";
import "./styles.css";

const client = new QueryClient();
const rootRoute = createRootRoute({ component: () => <Outlet /> });
const workspaceRoute = createRoute({ getParentRoute: () => rootRoute, path: "/", component: Workspace });
const router = createRouter({ routeTree: rootRoute.addChildren([workspaceRoute]) });
declare module "@tanstack/react-router" { interface Register { router: typeof router } }

function Workspace() {
  const qc = useQueryClient(); const draft = useDraft();
  const assets = useQuery({ queryKey: ["assets"], queryFn: api.assets });
  const jobs = useQuery({ queryKey: ["jobs"], queryFn: api.jobs, refetchInterval: (q) => q.state.data?.some((j) => isActive(j.status)) ? 1500 : false });
  const [selected, setSelected] = useState<string>(); const [notice, setNotice] = useState("");
  const selectedAsset = assets.data?.find((a) => a.id === selected);
  const save = useMutation({ mutationFn: async () => saveAsset(selectedAsset?.id, { name: draft.assetName, prompt: draft.prompt }), onSuccess: (a) => { draft.set({ assetId: a.id }); setSelected(a.id); qc.invalidateQueries({ queryKey: ["assets"] }); setNotice("Asset saved"); }, onError: (e) => setNotice((e as Error).message) });
  const archive = useMutation({ mutationFn: api.archiveAsset, onSuccess: () => { qc.invalidateQueries({ queryKey: ["assets"] }); draft.reset(); setSelected(undefined); } });
  const submit = useMutation({ mutationFn: () => api.createJob({ assetId: draft.assetId, assetName: draft.assetName, prompt: draft.prompt, ...draft.options }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["jobs"] }); setNotice("Job queued") }, onError: (e) => setNotice((e as Error).message) });
  useEffect(() => { if (selectedAsset) draft.set({ assetId: selectedAsset.id, assetName: selectedAsset.name, prompt: selectedAsset.prompt }); }, [selectedAsset?.id]);
  return <div className="app"><header><div className="logo">STICKER<br /><span>ROLLER</span></div><div><p className="eyebrow">LOCAL CREATIVE WORKBENCH</p><h1>Make something loud.</h1></div><Link to="/" className="refresh" onClick={() => { assets.refetch(); jobs.refetch(); }}>↻ refresh</Link></header>
    <div className="layout"><aside><div className="section-title"><span>TEXT ASSETS</span><button className="icon" onClick={() => { draft.reset(); setSelected(undefined); }}>＋</button></div>{assets.isLoading ? <div className="skeleton">Loading assets…</div> : assets.data?.length ? assets.data.map((a) => <button className={`asset ${a.id === selected ? "selected" : ""}`} key={a.id} onClick={() => setSelected(a.id)}><strong>{a.name}</strong><small>{a.prompt.slice(0, 54)}</small></button>) : <div className="empty">No assets yet.<br />Create your first prompt →</div>}</aside>
      <main><section className="editor panel"><div className="panel-head"><div><p className="eyebrow orange">PROMPT EDITOR</p><h2>{selectedAsset ? "Edit asset" : "New text asset"}</h2></div>{selectedAsset && <button className="danger" onClick={() => archive.mutate(selectedAsset.id)}>Archive</button>}</div><label>ASSET NAME<input value={draft.assetName} onChange={(e) => draft.set({ assetName: e.target.value })} /></label><label>PROMPT <span className="hint">job edits stay private until saved</span><textarea value={draft.prompt} onChange={(e) => draft.set({ prompt: e.target.value })} placeholder="Describe the sticker you want to create…" /></label><div className="actions"><button className="secondary" disabled={save.isPending} onClick={() => save.mutate()}>Save asset</button><button className="primary" disabled={submit.isPending || !draft.prompt.trim()} onClick={() => submit.mutate()}>{submit.isPending ? "Submitting…" : "Generate stickers →"}</button></div>{notice && <p className="notice">{notice}</p>}</section>
      <Toolbar /><History jobs={jobs.data ?? []} loading={jobs.isLoading} /></main></div></div>;
}
function Toolbar() { const draft = useDraft(); const setOption = (key: string, value: string | boolean | number) => draft.set({ options: { ...draft.options, [key]: value } }); return <section className="toolbar panel"><div className="panel-head"><div><p className="eyebrow blue">GENERATION PARAMETERS</p><h2>Dial it in.</h2></div></div><div className="fields"><label>MODEL<select value={draft.options.model} onChange={(e) => setOption("model", e.target.value)}><option>gemini-3-pro-image</option><option>gemini-3.1-flash-image-preview</option></select></label><label>RATIO<select value={draft.options.aspectRatio} onChange={(e) => setOption("aspectRatio", e.target.value)}>{["1:1","16:9","9:16","4:3","3:4"].map((x) => <option key={x}>{x}</option>)}</select></label><label>SIZE<select value={draft.options.imageSize} onChange={(e) => setOption("imageSize", e.target.value)}>{["1K","2K","4K"].map((x) => <option key={x}>{x}</option>)}</select></label><label>COUNT<input type="number" min="1" max="20" value={draft.options.count} onChange={(e) => setOption("count", Number(e.target.value))} /></label><label className="check"><input type="checkbox" checked={draft.options.removeBackground} onChange={(e) => setOption("removeBackground", e.target.checked)} /> Remove background</label></div></section> }
function History({ jobs, loading }: { jobs: Array<{ id: string; assetName: string; promptSnapshot: string; requestedCount: number; status: string; completedCount: number; failedCount: number; createdAt: string }>; loading: boolean }) { const qc = useQueryClient(); return <section className="history"><div className="history-title"><div><p className="eyebrow purple">DURABLE JOB HISTORY</p><h2>Recent generations</h2></div><span>{jobs.length} jobs</span></div>{loading ? <div className="empty">Loading history…</div> : !jobs.length ? <div className="empty">Your submitted jobs will appear here.</div> : jobs.map((job) => <JobCard key={job.id} job={job} refresh={() => qc.invalidateQueries({ queryKey: ["jobs"] })} />)}</section> }
function JobCard({ job, refresh }: { job: { id: string; assetName: string; promptSnapshot: string; requestedCount: number; status: string; completedCount: number; failedCount: number; createdAt: string }; refresh: () => void }) { const detail = useQuery({ queryKey: ["job", job.id], queryFn: () => api.job(job.id), refetchInterval: isActive(job.status) ? 1500 : false }); const cancel = useMutation({ mutationFn: api.cancel, onSuccess: refresh }); const retry = useMutation({ mutationFn: api.retry, onSuccess: refresh }); const full = detail.data as Job | undefined; const items = full?.items ?? []; return <article className="job"><div className="job-head"><div><strong>{job.assetName}</strong><small>{new Date(job.createdAt).toLocaleString()}</small></div><span className={`status ${job.status}`}>{job.status}</span></div><p>{job.promptSnapshot}</p><div className="progress"><span style={{ width: `${job.requestedCount ? job.completedCount / job.requestedCount * 100 : 0}%` }} /></div><small>{job.completedCount}/{job.requestedCount} complete {job.failedCount ? `· ${job.failedCount} failed` : ""}</small><div className="results">{items.map((item) => <div className={`result ${item.status}`} key={item.id}>{item.status === "succeeded" ? <>{item.files?.[0] ? <img className="preview" src={`/api/output/${encodeURIComponent(item.files[0].fileName)}`} alt="Generated sticker" /> : <div className="preview">Image ready</div>}<a href={item.files?.[0] ? `/api/output/${encodeURIComponent(item.files[0].fileName)}` : "#"} download>Preview / download</a></> : item.status === "failed" ? <span>⚠ {item.error ?? "Generation failed"}</span> : <span>{item.status}…</span>}</div>)}</div><div className="job-actions">{isActive(job.status) && <button onClick={() => cancel.mutate(job.id)}>Cancel</button>}{job.status === "failed" && <button onClick={() => retry.mutate(job.id)}>Retry failed</button>}</div></article> }
function App() { return <QueryClientProvider client={client}><RouterProvider router={router} /></QueryClientProvider> }

createRoot(document.getElementById("root")!).render(<App />);
