import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Outlet, RouterProvider, createRootRoute, createRoute, createRouter } from "@tanstack/react-router";
import { api, isActive, useDraft, type Job } from "./api";
import { Button } from "./components/ui/Button";
import { Card } from "./components/ui/Card";
import { Badge } from "./components/ui/Badge";
import { Select } from "./components/ui/Select";
import { Dialog } from "./components/ui/Dialog";
import { Composer } from "./components/Composer";
import type { JobRow } from "../../src/web-types";
import "./styles.css";
const client=new QueryClient(); const rootRoute=createRootRoute({component:()=> <Outlet/>}); const workspaceRoute=createRoute({getParentRoute:()=>rootRoute,path:"/",component:Workspace}); const router=createRouter({routeTree:rootRoute.addChildren([workspaceRoute])}); declare module "@tanstack/react-router" { interface Register { router:typeof router } }
function Workspace(){ const qc=useQueryClient(); const draft=useDraft(); const assets=useQuery({queryKey:["assets"],queryFn:api.assets}); const jobs=useQuery({queryKey:["jobs"],queryFn:api.jobs,refetchInterval:q=>q.state.data?.some(j=>isActive(j.status))?1500:false}); const [dialog,setDialog]=useState(false); const [notice,setNotice]=useState(""); const save=useMutation({mutationFn:api.createAsset,onSuccess:()=>{setDialog(false);qc.invalidateQueries({queryKey:["assets"]});setNotice("素材已保存")},onError:e=>setNotice((e as Error).message)}); const submit=useMutation({mutationFn:()=>api.createJob({authoredPrompt:draft.prompt,referencedAssetIds:draft.referencedAssetIds,...draft.options}),onSuccess:()=>{qc.invalidateQueries({queryKey:["jobs"]});draft.reset();setNotice("任务已提交")},onError:e=>setNotice((e as Error).message)}); return <div className="app"><header><div className="brand">生图<br/><span>工作室</span></div><div><p className="eyebrow">LOCAL CREATIVE WORKBENCH</p><h1>把素材组合成任务</h1></div><Button variant="ghost" onClick={()=>{assets.refetch();jobs.refetch()}}>↻ 刷新</Button></header><main><Composer assets={assets.data??[]} onCreate={()=>setDialog(true)}/><Card className="toolbar"><Select value={draft.options.model} onChange={e=>draft.set({options:{...draft.options,model:e.target.value}})}><option>gemini-3-pro-image</option><option>gemini-3.1-flash-image-preview</option></Select><Select value={`${draft.options.aspectRatio} / ${draft.options.imageSize}`} onChange={e=>{const [aspectRatio,imageSize]=e.target.value.split("/");draft.set({options:{...draft.options,aspectRatio:aspectRatio!.trim(),imageSize:imageSize!.trim()}})}}><option>1:1 / 1K</option><option>1:1 / 2K</option><option>16:9 / 2K</option><option>9:16 / 2K</option></Select><Button variant="secondary" disabled title="Phase 1 仅支持文本素材">添加图片（暂不可用）</Button><Button variant="secondary" onClick={()=>setNotice("更多参数：可在此调整张数与背景")}>更多参数</Button><Button disabled={submit.isPending||!draft.prompt.trim()} onClick={()=>submit.mutate()}>{submit.isPending?"提交中…":"提交任务"}</Button></Card>{notice&&<p className="notice">{notice}</p>}<History jobs={jobs.data??[]} loading={jobs.isLoading}/></main><MaterialDialog open={dialog} onClose={()=>setDialog(false)} onSave={body=>save.mutate(body)}/></div> }
function MaterialDialog({open,onClose,onSave}:{open:boolean;onClose:()=>void;onSave:(b:{name:string;prompt:string;category:string})=>void}){const [name,setName]=useState("");const [prompt,setPrompt]=useState("");const [category,setCategory]=useState("提示词");return <Dialog open={open} title="创建可复用素材" onClose={onClose}><label>名称<input value={name} onChange={e=>setName(e.target.value)}/></label><label>内容<textarea value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><label>分组<input value={category} onChange={e=>setCategory(e.target.value)}/></label><Button disabled={!name.trim()||!prompt.trim()} onClick={()=>onSave({name,prompt,category})}>保存素材</Button></Dialog>}
function History({jobs,loading}:{jobs:JobRow[];loading:boolean}){if(loading)return <section className="history"><div className="empty">正在加载任务…</div></section>;if(!jobs.length)return <section className="history"><h2>任务历史</h2><div className="empty">提交任务后，图片结果会显示在这里</div></section>;return <section className="history"><div className="history-title"><h2>任务历史</h2><span>{jobs.length} 个任务</span></div>{jobs.map(j=><JobCard key={j.id} job={j}/>)}</section>}
function JobCard({job}:{job:JobRow}){const qc=useQueryClient();const detail=useQuery({queryKey:["job",job.id],queryFn:()=>api.job(job.id),refetchInterval:isActive(job.status)?1500:false});const cancel=useMutation({mutationFn:api.cancel,onSuccess:()=>qc.invalidateQueries({queryKey:["jobs"]})});const retry=useMutation({mutationFn:api.retry,onSuccess:()=>qc.invalidateQueries({queryKey:["jobs"]})});const full=detail.data;return <article className="job"><div className="history-title"><div><strong>{new Date(job.createdAt).toLocaleString()}</strong><small>（{job.requestedCount} 张）</small></div><Badge className={`status-${job.status}`}>{job.status}</Badge></div><p>{job.promptSnapshot}</p><div className="results">{(full?.items??[]).map(item=><div className="result" key={item.id}>{item.status==="succeeded"&&item.files?.[0]?<img src={`/api/output/${encodeURIComponent(item.files[0].fileName)}`} alt="生成结果"/>:<span>{item.status==="failed"?`失败：${item.error??"未知错误"}`:item.status}</span>}</div>)}</div><div className="job-actions">{isActive(job.status)&&<Button variant="secondary" onClick={()=>cancel.mutate(job.id)}>取消</Button>}{job.status==="failed"&&<Button variant="secondary" onClick={()=>retry.mutate(job.id)}>重试失败项</Button>}</div></article>}
function App(){return <QueryClientProvider client={client}><RouterProvider router={router}/></QueryClientProvider>};createRoot(document.getElementById("root")!).render(<App/>);
